language: android
android:
  components:
  - platform-tools
  - tools
  - build-tools-28.0.3
  - android-26
  - extra-android-m2repository
jdk: oraclejdk8
script:
- "./gradlew clean thinr:assembleDebug  thinrtest:jacocoinstrument thinrtest:testDebugUnitTest thinrtest:jacocoreport thinrtest:coveralls"
