language: android
android:
  components:
  - platform-tools
  - tools
  - build-tools-26.0.2
  - android-23
  - extra-android-m2repository
jdk: oraclejdk8
script:
- "./gradlew clean thinr:assembleDebug  thinrtest:jacocoinstrument thinrtest:testDebugUnitTest thinrtest:jacocoreport thinrtest:coveralls"
